services:
  webapp:
    build: .
    container_name: django-app
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    environment:
      AWS_REGION: ${AWS_REGION}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
