# Generated by Django 5.1.1 on 2024-09-19 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of analysis', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='File path on the server or storage', max_length=255)),
                ('uri', models.CharField(help_text='File URI (uniform resource identifier)', max_length=255)),
                ('url', models.URLField(help_text='Publicly accessible URL to the file', max_length=500)),
                ('tags', models.JSONField(blank=True, help_text='Tags as a JSON array', null=True)),
                ('size', models.BigIntegerField(help_text='File size in bytes')),
                ('analysis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app.analysis')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
    ]
